import React from "react";
import Image from "next/image";
import { FaStar } from "react-icons/fa6";
import CourseCard from "@/components/CourseCard";

export const metadata = {
  title: "Course details",
  description: "Generated by create next app",
};

const getCourses = async () => {
  const res = await fetch("http://localhost:5004/all-courses", {
    cache: "force-cache",
  });
  return res.json();
};

const CourseDetaisPage = async ({ params }) => {
  const { courseId } = await params;

  const res = await fetch(`http://localhost:5004/all-courses/${courseId}`);
  const course = await res.json();
  console.log(course);

  const courses = await getCourses();

  return (
    <div className="container mx-auto mt-[5vh]">
      <div className="flex flex-col md:flex-row mb-14">
        <figure className="w-[50vw] rounded-sm ">
          <Image className="w-[100%] rounded-sm" src={course.image} width={1000} height={1000} alt="Movie" />
        </figure>

        <div className="card-body max-w=[50%]">
          <h1 className="text-3xl font-bold mb-4">{course.title}</h1>

          <h2 className="text-xl mt-2">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad
            blanditiis laboriosam hic aut nam facere molestias cum quis magnam
            veniam? Non cum, libero aspernatur temporibus, nihil exercitationem,
            quia perspiciatis harum commodi ratione totam sit recusandae quae
            hic repellendus dicta. Consectetur officia nihil delectus quae ut
            repellat veniam, assumenda et illum.
          </h2>

          <p className="text-xl font-bold mb-3">
            Instructor : {course.instructor}
          </p>
          <div className="card-actions justify-between">
            <div className="flex gap-1 items-center text-lg">
              <FaStar /> {course.rating}{" "}
            </div>
            <button className="btn btn-primary">Enrole Now</button>
          </div>
        </div>
      </div>

       <h1 className="text-2xl font-bold mb-8 ">More Course</h1>

      <div className=" grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4  ">

        {courses.slice(0,4).map((course) => (
          <CourseCard key={course.id} course={course} />
        ))}

      </div>
    </div>
  );
};

export default CourseDetaisPage;