import React from 'react'


export const metadata = {
  title: "Course details",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <h6>Course details page </h6>
    </div>
  )
}

export default page
