import Image from "next/image";
import React from "react";
import person from "../../../public/instructors/instructor_1.png";


import { auth } from '@/lib/auth';
import { headers } from 'next/headers';
import { redirect } from 'next/navigation';



// export const metadata = {
//   title: "Profile",
//   description: "Generated by create next app",
// };



const MyProfilePage = async () => {
  
  const session = await auth.api.getSession({
    headers: await headers()
  })

  console.log('session data in course page' ,session);

  const user = session?.user;
  if(!user){
    redirect ('/signup');
    // return <div>Please Sign in to access to the course page</div>
  }


  return (
    <div className="shadow-2xl rounded-lg px-20 py-16 container mx-auto grid gap-2 md:gap-4 mt-10 grid-cols-1 md:grid-cols-2">

      <div className=" px-6 py-4 text-center card">
        <Image
          width={120}
          height={250}
          src={person}
          alt={"profile image"}
          className="w-36 rounded-sm mx-auto mb-4"
        />
        <h1 className="text-2xl font-bold ">Masfiqur Rahman</h1>
        <p>example@gmail.com</p>

        <button className="btn bg-orange-400 text-white rounded-md">Update Profile</button>
      </div>


      <div className="flex flex-col gap-10 md:gap-4 card">
        <div className="card px-8 py-10 ">
          <h1 className="text-xl font-bold mb-6">Enrole Courses</h1>
          <div>
            <h2 className="text-lg font-normal bg-pink-100">Mern Stack Developer</h2>
          </div>
        </div>
        <div className="card">d</div>
      </div>
    </div>


    
  );
};

export default MyProfilePage;
