import React from 'react'

export const metadata = {
  title: "Profile",
  description: "Generated by create next app",
};
const MyProfilePage = () => {
  return (
    <div className='container mx-auto grid gap-2 md:gap-4 grid-cols-1 md:grid-cols-2'>
      <div className='bg-pink-100'>section 1</div>
      <div className='bg-purple-100'>section 2</div>
    </div>
  )
}

export default MyProfilePage
