// 'use client'

import CourseCard from '@/components/CourseCard';
import { auth } from '@/lib/auth';
import { headers } from 'next/headers';
import { redirect } from 'next/navigation';
import { CiSearch } from "react-icons/ci";

export const metadata = {
  title: "Courses",
  description: "Generated by create next app",
};


const getCourses = async () =>{
  const res = await fetch('http://localhost:5004/all-courses' )
  return res.json();
}


const CoursePage = async () => {
  
  const session = await auth.api.getSession({
    headers: await headers()
  })

  console.log('session data in course page' ,session);

  const user = session?.user;
  if(!user){
    redirect ('/signup');
    // return <div>Please Sign in to access to the course page</div>
  }
  const courses = await getCourses();
  
  return (
    <div className='container mx-auto mt-[5vh]'>

      <div className='flex justify-between mb-4 '>

        <h1 className='text-3xl font-bold'>All Course </h1>
        <div className="flex align-middle md:block rounded-lg px-3 py-2 items-center gap-3 border-gray-600 border">
          <input type="text" placeholder="Search" className="border-0 outline-0" />

          <button className='cursor-pointer font-bold'>
            <CiSearch width={100}  />
          </button>
        </div>

      </div>

      <div className=' grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6'>
        {
          courses.map((course) =>(
          <CourseCard key={course.id} course={course}/>
          ))
        }
      </div>
    </div>
  )
}

export default CoursePage
