import { courses } from '../../../../data/courses';
import CourseCard from '@/components/CourseCard';


export const metadata = {
  title: "Courses",
  description: "Generated by create next app",
};

const CoursePage = () => {
  return (
    <div>
      {/* <h6>Course Page</h6> */}
      <div className='grid gap-6 grid-cols-3 wrap'>
        {
          courses.map((course) =>(
          <CourseCard key={course.id} course={course}/>
          ))
        }
      </div>
    </div>
  )
}

export default CoursePage
