import { courses } from '../../../../data/courses';
import CourseCard from '@/components/CourseCard';


export const metadata = {
  title: "Courses",
  description: "Generated by create next app",
};

const CoursePage = () => {
  return (
    <div className='container mx-auto '>
      {/* <h6>Course Page</h6> */}
      <div className=' grid grid-cols-4 md:grid-cols-3 lg:grid-cols-4 gap-6'>
        {
          courses.map((course) =>(
          <CourseCard key={course.id} course={course}/>
          ))
        }
      </div>
    </div>
  )
}

export default CoursePage
