// import { courses } from '../../../../data/courses';
import CourseCard from '@/components/CourseCard';

export const metadata = {
  title: "Courses",
  description: "Generated by create next app",
};


const getCourses = async () =>{
  const res = await fetch('http://localhost:5004/all-courses' , {cache:'force-cache'})
  return res.json();
}

const CoursePage = async () => {

  const courses = await getCourses();
  
  return (
    <div className='container mx-auto '>
      {/* <h6>Course Page</h6> */}
      <div className=' grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6'>
        {
          courses.map((course) =>(
          <CourseCard key={course.id} course={course}/>
          ))
        }
      </div>
    </div>
  )
}

export default CoursePage
